# Use an official Python runtime as the base image
FROM python:3.11-slim

# Install procps, which includes pgrep
RUN apt-get update && \
    apt-get install -y procps openssh-client && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /root/warnet

# Copy the source directory contents into the container
COPY . /root/warnet
RUN pip install .

# Make port 9276 available to the world outside this container
# Change the port if your server is running on a different port
EXPOSE 9276

# Run server.py when the container launches
CMD ["warnet", "--backend=k8s"]
