{
 "title": "Bitcoin RPC scraper",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of txns requested for compact block",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time({container=~\".+tank.+\"} |= `Successfully reconstructed block` | regexp `.*\\s(?P<txrequested>[0-9]+)\\stxn\\srequested.*` | unwrap txrequested | __error__=\"\"[3m])"
    }
   ]
  },
  {
   "title": "Mempool Size (# Txs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    { "expr": "bitcoin_mempool_size", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Outbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "bitcoin_conn_out", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Inbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "bitcoin_conn_in", "legendFormat": "{{job}}" }
   ]
  }
 ]
}