FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y ccache python3 vim build-essential wget sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p /root/.bitcoin

ARG ARCH
ARG BITCOIN_URL
ARG BITCOIN_VERSION

RUN wget $BITCOIN_URL && \
    tar -xzf bitcoin-${BITCOIN_VERSION}-${ARCH}-linux-gnu.tar.gz -C /usr/local --strip-components=1

WORKDIR /root/.bitcoin

#EXPOSE 18444 18443
#EXPOSE 8332 8333

CMD ["/usr/local/bin/bitcoind", "--datadir=/root/.bitcoin", "--conf=/root/.bitcoin/bitcoin.conf"]

