FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

RUN apt-get update && \
    apt-get install -y gcc libpq-dev build-essential libffi-dev python-dev-is-python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt

RUN useradd --create-home myuser
USER myuser

WORKDIR /app

COPY . /app

EXPOSE 80
