# Default values for btcd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: warnet

restartPolicy: Never

image:
  repository: lucasdbr05/btcd
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podLabels:
  app: "warnet"
  mission: "tank"

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  exec:
    command:
      - pidof
      - btcd
  failureThreshold: 12
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 10
readinessProbe:
  failureThreshold: 12
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 10

# Node data persistence configuration
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOncePod
  size: 20Gi
  existingClaim: ""

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

collectLogs: false
metricsExport: false
prometheusMetricsPort: 9332

global:
  chain: regtest
  regtest:
    RPCPort: 18443
    RPCListenPort: 18334
    P2PPort: 18444
  signet:
    RPCPort: 38332
    RPCListenPort: 38334
    P2PPort: 38333
  testnet:
    RPCPort: 18332
    RPCListenPort: 18334
    P2PPort: 18333
  mainnet:
    RPCPort: 8332
    RPCListenPort: 8334
    P2PPort: 8333
  rpcuser: user
  rpcpassword: gn0cchi

# btcd configuration flags (passed as CLI args)
# btcd does not use a config file in the same way as Bitcoin Core
extraArgs: ""

config: ""

addnode: []

loadSnapshot:
  enabled: false
  url: ""
