FROM debian:bookworm-slim as builder
ENV DEBIAN_FRONTEND=noninteractive

ARG REPO
ARG BRANCH
ARG BUILD_ARGS

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        wget \
        git \
        automake \
        autotools-dev \
        build-essential \
        libtool \
        libboost-dev \
        libevent-dev \
        libdb5.3++-dev \
        libminiupnpc-dev \
        libnatpmp-dev \
        libzmq3-dev \
        libsqlite3-dev \
        pkg-config \
    && rm -rf /var/lib/apt/lists/*  # Clean up to reduce image size

# Copy the patch into the container
COPY isroutable.patch /tmp/

# Clone, patch, and build
RUN set -ex \
    && mkdir build \
    && cd build \
    && git clone --depth 1 --branch "${BRANCH}" "https://github.com/${REPO}" \
    && cd bitcoin \
    && git apply /tmp/isroutable.patch \
    && ./autogen.sh \
    && ./configure ${BUILD_ARGS} \
    && make -j$(nproc) \
    && make install

# Shrink image size with a second stage
FROM debian:bookworm-slim

ARG UID=3338
ARG GID=3338
ARG TOR=0
ARG WARNET=0
ARG BITCOIN_ARGS
# env var overrides
ENV UID=$UID
ENV GID=$GID
ENV BITCOIN_DATA=/home/bitcoin/.bitcoin
ENV BITCOIN_ARGS=$BITCOIN_ARGS
ENV TOR=$TOR
ENV WARNET=$WARNET

RUN set -ex \
    && groupadd --gid ${GID} bitcoin \
    && useradd --create-home --no-log-init -u ${UID} -g ${GID} bitcoin \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        dnsutils \
        gosu \
        iproute2 \
        tor \
        libboost-dev \
        libevent-dev \
        libdb5.3++-dev \
        libminiupnpc-dev \
        libnatpmp-dev \
        libzmq3-dev \
        libsqlite3-dev \
    && apt-get clean \
    && rm -rf /var/cache/apt/* /var/lib/apt/lists/*

COPY --from=builder /usr/local/bin/bitcoind /usr/local/bin/bitcoin-cli /usr/local/bin/
COPY entrypoint.sh /entrypoint.sh
# Warnet torrc using test network
COPY torrc /etc/tor/warnet-torr

VOLUME ["/home/bitcoin/.bitcoin"]
EXPOSE 8332 8333 18332 18333 18443 18444 38333 38332

ENTRYPOINT ["/entrypoint.sh"]
CMD echo bitcoind -version
CMD ["bitcoind"]
