FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

ARG REPO
ARG BRANCH

# Base requirements
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        #
        # general packages
        #
        ccache \
        ca-certificates \
        python3 \
        vim \
        build-essential \
        wget \
        tor \
        iproute2 \
        gosu \
        #
        # For building bitcoin core
        #
        autotools-dev \
        libtool \
        automake \
        pkg-config \
        libboost-dev \
        libevent-dev \
        libdb5.3++-dev \
        libminiupnpc-dev \
        libnatpmp-dev \
        libzmq3-dev \
        libqrencode-dev \
        libsqlite3-dev \
        git \
    && apt-get clean

# Build from source
RUN if [ -n "${REPO}" ]; then \
        mkdir build; \
        cd /build; \
        git clone --depth 1 --branch "${BRANCH}" "https://github.com/${REPO}"; \
        cd /build/bitcoin; \
        ./autogen.sh; \
        ./configure \
            --disable-tests \
            --without-gui \
            --disable-bench \
            --disable-fuzz-binary \
            --enable-suppress-external-warnings; \
        make -j$(nproc); \
        make install; \
    fi

# Create bitcoin and debian-tor users
RUN groupadd -r bitcoin && useradd -r -m -g bitcoin bitcoin


# Tor setup
RUN mkdir -p /home/debian-tor/.tor/keys \
    && chown -R debian-tor:debian-tor /home/debian-tor \
    && chown -R debian-tor:debian-tor /etc/tor

COPY tor-keys/* /home/debian-tor/.tor/keys/

# Bitcoind setup
RUN usermod -a -G debian-tor bitcoin
RUN mkdir -p /home/bitcoin/.bitcoin \
    && chown -R bitcoin:bitcoin /home/bitcoin

CMD gosu debian-tor tor & \
    gosu bitcoin /usr/local/bin/bitcoind --datadir=/home/bitcoin/.bitcoin --conf=/home/bitcoin/.bitcoin/bitcoin.conf
