apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commander.fullname" . }}-warnet
  labels:
    {{- include "commander.labels" . | nindent 4 }}
binaryData:
  warnet.json: {{ .Values.warnet }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commander.fullname" . }}-archive
  labels:
    {{- include "commander.labels" . | nindent 4 }}
binaryData:
  archive.pyz: {{ .Values.archive }}