apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commander.fullname" . }}-command
  labels:
    {{- include "commander.labels" . | nindent 4 }}
binaryData:
  command: {{ .Values.command }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commander.fullname" . }}-warnet
  labels:
    {{- include "commander.labels" . | nindent 4 }}
binaryData:
  warnet.json: {{ .Values.warnet }}
