FROM debian:bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y tor iproute2 gosu

RUN mkdir -p /home/debian-tor/.tor/keys
RUN chown -R debian-tor:debian-tor /home/debian-tor
RUN mkdir -p /var/log/tor
RUN chown -R debian-tor:debian-tor /var/log/tor

COPY tor/torrc.relay /etc/tor/torrc

EXPOSE 9050

COPY tor/tor-entrypoint.sh /entrypoint.sh
ENTRYPOINT /entrypoint.sh
CMD ["tor", "-f", "/etc/tor/torrc"]
