apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoincore.fullname" . }}
  labels:
    {{- include "bitcoincore.labels" . | nindent 4 }}
data:
  bitcoin.conf: |
    {{ .Values.global.chain }}=1

    {{ template "bitcoincore.check_semver" . }}
    {{- .Values.baseConfig | nindent 4 }}
    rpcport={{ index .Values.global .Values.global.chain "RPCPort" }}
    rpcpassword={{ .Values.global.rpcpassword }}
    zmqpubrawblock=tcp://0.0.0.0:{{ .Values.global.ZMQBlockPort }}
    zmqpubrawtx=tcp://0.0.0.0:{{ .Values.global.ZMQTxPort }}
    {{- .Values.defaultConfig | nindent 4 }}
    {{- .Values.config | nindent 4 }}
    {{- range .Values.addnode }}
      {{- print "addnode=" . | nindent 4}}
    {{- end }}
