FROM alpine

RUN apk add bash tor

RUN mkdir -p /etc/tor/keys

RUN mkdir -p /var/log/tor

COPY src/templates/tor/tor-keys /etc/tor/keys
COPY src/templates/tor/torrc.da /etc/tor/torrc
COPY src/templates/tor/tor-da-entrypoint.sh /entrypoint.sh

EXPOSE 9050

RUN chown -R tor /etc/tor
RUN chown -R tor /var/log/tor
USER tor

ENTRYPOINT ["/entrypoint.sh"]
