FROM debian:bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y tor

RUN mkdir -p /home/debian-tor/.tor/keys
RUN chown -R debian-tor:debian-tor /home/debian-tor
RUN mkdir -p /var/log/tor
RUN chown -R debian-tor:debian-tor /var/log/tor

COPY tor/tor-keys /home/debian-tor/.tor/keys
RUN chown -R debian-tor:debian-tor /home/debian-tor/.tor/keys
COPY tor/torrc.da /etc/tor/torrc

EXPOSE 9050

USER debian-tor
CMD ["tor", "-f", "/etc/tor/torrc"]
