{
 "title": "Bitcoin RPC scraper",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mempool Size (# Txs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "bitcoin_mempool_size", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Outbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "bitcoin_conn_out", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Inbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "bitcoin_conn_in", "legendFormat": "{{job}}" }
   ]
  }
 ]
}