FROM debian:bookworm-slim
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y tor iproute2 dnsutils

RUN mkdir -p /home/debian-tor/.tor
RUN chown -R debian-tor:debian-tor /home/debian-tor
RUN mkdir -p /var/log/tor
RUN chown -R debian-tor:debian-tor /var/log/tor


COPY ./torrc.relay /etc/tor/torrc

COPY ./tor-entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
