{
 "title": "Default Warnet Dashboard",
 "refresh": "5s",
 "panels": [
  {
   "title": "Outbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "outbounds", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Inbound connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "inbounds", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Mempool size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "mempool_size", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "blocks", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}