{
 "title": "Sample Warnet Dashboard (LND)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Channel Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "lnd_balance_channels", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "lnd_peers", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "LND Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "lnd_block_height", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}